defaults:
  - umi
  - _self_

name: umi_lerobot
dataset_path: data/umi_lerobot
repo_id: local/umi_abs

dataset:
  _target_: diffusion_policy.dataset.dataloader_lerobot.UmiDatasetLeRobot
  shape_meta: ${task.shape_meta}
  dataset_path: ${task.dataset_path}
  repo_id: ${task.repo_id}
  pose_repr: ${task.pose_repr}
  action_padding: false
  temporally_independent_normalization: false
  repeat_frame_prob: 0.0
  max_duration: null
  normalizer_num_workers: 0
  seed: 42
  val_ratio: 0.05
  video_backend: pyav
  image_transform:
    _target_: diffusion_policy.dataset.image_augmentation.SequenceImageAugmentor
    image_shape: [224, 224]
    transforms:
      - type: RandomCrop
        ratio: 0.95
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.3
        contrast: 0.4
        saturation: 0.5
        hue: 0.08
