defaults:
  - umi
  - _self_

name: umi_lerobot
dataset_path: data/umi_lerobot

dataset:
  _target_: diffusion_policy.dataset.dataloader_lerobot.UmiDatasetLeRobot
  shape_meta: ${task.shape_meta}
  dataset_path: ${task.dataset_path}
  action_padding: false
  temporally_independent_normalization: false
  max_duration: null
  normalizer_num_workers: 0
  seed: 42
  val_ratio: 0.05
  video_backend: pyav
